name: Build and Upload to S3

on:
  workflow_dispatch:

jobs:
  build-upload:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '18'
      S3_BUCKET: nms-codebuild-bucket
      AWS_REGION: ap-south-1
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0    
        
    - name: Extract branch name
      shell: bash
      run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
      id: extract_branch        

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
      
    - name: Cache the dependencies
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-      

    - name: Install dependencies
      run: yarn --prefer-offline

    - name: Build
      run: yarn build

    - name: Deploy
      if: success()
      run: |
        aws s3 rm s3://${{ env.S3_BUCKET }}/${{ steps.extract_branch.outputs.branch }} --recursive
        aws s3 sync ./dist/test-github-action s3://${{ env.S3_BUCKET }}/${{ steps.extract_branch.outputs.branch }}
